# Generated by Django 4.1.5 on 2023-01-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_box_alter_card_options_alter_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['time_create']},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('W', 'Word'), ('T', 'Term'), (None, 'Choise card type')], max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
