# Generated by Django 4.1.5 on 2023-01-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_delete_box_alter_card_options_alter_card_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('W', 'Word'), ('T', 'Term'), (None, 'Choose card type')], max_length=1),
        ),
    ]
